### PR TITLE
Dev change deinstallation into a more gentle one

### PR DESCRIPTION
**Pull request by nbehrnd**
If choosing to opt-out of vsteno, the basically rewritten script `deinstall_tools.sh` now proceeds stepwise and requests for each step the explicit confirmation by the user.  Thus -- contrary to the earlier version -- one should no longer loose a «vsteno tool» if this (already) is used in a different project (e.g., the spell checker, git, etc.).

I didn't set up vsteno locally because the space required for mysql and apache2 currently is used on my computer by other data.  Thus, I recommend this script's testing extended by you about these two larger tools of vsteno, too.

### CODE REVIEW

**Comment by nbehrnd** [comment]
My first two complete cycles running `install_tools.sh` and `deinstall_tools.sh` reveal script `deinstall_tools.sh` does remove from all of the tools varying portions.  Git and hunspell dictionaries are the ones removed well, while `sudo apt autoremove` still recognizes a significant amount (ca. 250 MB) of other data (mostly mysql related I wasn't able to test earlier) to be cleared in addition to what the script already does / tries.  Thus, script `deinstall_tools.sh` requires some work by mine tomorrow.

**Comment by nbehrnd** [comment]
By the commit «extend scope of gentle deinstallation script», script `deinstall_tools.sh` offers a better cleaning, than the initial version of this pull request.  If agreeing to remove all of the libraries `downloads/install_tools.sh` installs (up to 385MB), now only about 1.6MB remains to be removed by `sudo apt autoremove`; basically, a few Perl libraries.   Checked to work fine (two complete cycles, Debian 10).

**Comment by marcelmaci** [comment]
Hi nbehrnd,
Thx for the completed script and testing. Looks nice to me. The only thing I'd improve is to offer a "default" option for each section, which basically leaves all system tools - apache, php, mysql, hunspell (including dictionaries), espeak etc. - and only removes VSTENO if the user just presses return (for commodity and to be sure that, by default, an unexperienced user doesn't accidently delete system tools).
Question: What ist mecab? Your script uninstalls it, but VSTENO doesn't install / need it (as far as I know - unless it's a dependency of hunspell or espeak)?

**Comment by nbehrnd** [comment]
Hi Marcel Maci,

offering a choice between removing only the acquired data, or (with
some degree of granularity) the tools and their data indeed would
improve the script further.  This requires to understand where data
specific to vsteno are stored; which possibly already is documented
in vsteno's manual, but obviously skipped by mine when writing
`deinstall_tools.sh` with only `install_tools.sh` in mind.  This
point is added to the desiderata.

Mecab, according to Debian's synaptic is a set of four libraries
installed `install_tools.sh` right after espeak for about 55MB,
described as «Japanese morphological analysis».[1]  So far, I only
speculate «Japanese» refers to the language(s) in Japan.  Redirecting
the installation log into a permanent record, it appears around line
#291 (two attachments).  Testing the installation of the tools individually
on the CLI, one by one, the mecab libraries are shown as dependency
in the larger chunk of 30 MB download / 242 MB platter space
needed when calling 

`sudo apt-get install mysql-server`.

This dependency is displayed even running `deinstall_tools.sh` to
remove all tools (incl. hunspell dicos and git) and issuing the install
command again.  I filed a ticket in Debian.


From an other project with Python based scripts, regiosqm, I
experience the automatic installation and resolution of dependencies
may depend on what package manager consider as necessary.  With
«standard CPython» from python.org / Debian repositories already
used, all is settled and ready-to-go with about 100MB used in
addition (about 50% documentation esp. for the larger libraries).
With separate acting Anaconda Python, I had to spend 1.1GB (about
700MB after installing conda's basic Python), because now the large
pandas library and its dependencies are equally fetched which I do
not have (nor need) in Debian's Python at all. _Maybe_ something
similar here.

[1] https://taku910.github.io/mecab/

[recorder_log.zip](https://github.com/marcelmaci/vsteno/files/5397736/recorder_log.zip)

**Comment by marcelmaci** [comment]
Hi nbehrnd,
Thx for your investigations.
1) mecab
Ok, seems to be a dependency from mysql (specific for japanese language, i.e. researches in database; as far as I know VSTENO doesn't need it). IMO, if the package manager installs it, it should be the PMs responsability to remove it ... :) If your script (tries to) desinstall(s) it (because the PM doesn't do it properly) that's fine.
2) data
Additional VSTENO specific data is indeed stored in the database. The initialization is done via ./php/init_db.php (plus includes dbpw.php and init_db_common.php). The tables created are documented in ./docs/documentation_v03.pdf (page 100). I can write a corresponding php-script (that deletes all tables before uninstalling mysql) and combine it with your bash-script for the next version - but this might take some time, because my first priority now is to work on models and books.

**Pull request closed without merging**
